from widgets.base_widget import BaseWidget
from widgets.label import Label
from widgets.button import Button
from widgets.inputbox import InputBox
from widgets.slider import Slider
from widgets.popup import Popup
from widgets.rgbselector import RGBSelector
from widgets.graph import GraphWidget
from widgets.accordion import Accordion
